
 
package HoursCalculatorSource;

/**
 *
 * @author Sergiu Borlovan
 */

public class HoursCalcGUI extends javax.swing.JFrame {

    
    public HoursCalcGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jStaffHoursInputPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDSField = new javax.swing.JTextField();
        jNDField = new javax.swing.JTextField();
        jSIField = new javax.swing.JTextField();
        jOCField = new javax.swing.JTextField();
        jAddField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jHolsField = new javax.swing.JTextField();
        jHoursWorkedPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTotalHrsField = new javax.swing.JTextField();
        jTopUpField = new javax.swing.JTextField();
        jTotalOCField = new javax.swing.JTextField();
        jTotalSIField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jOvertimeField = new javax.swing.JTextField();
        jGoButton = new javax.swing.JButton();
        jExitButton = new javax.swing.JButton();
        jClearButton = new javax.swing.JButton();
        jSettingsButton = new javax.swing.JButton();
        jPayPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPayField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Staff Hours Calculator");

        jStaffHoursInputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Shift input (shifts/days)"));

        jLabel2.setText("DS:");

        jLabel3.setText("ND:");

        jLabel4.setText("SI:");

        jLabel5.setText("OC:");

        jLabel6.setText("Additional hours:");

        jDSField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDSFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Holidays:");

        jHolsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHolsFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jStaffHoursInputPanelLayout = new javax.swing.GroupLayout(jStaffHoursInputPanel);
        jStaffHoursInputPanel.setLayout(jStaffHoursInputPanelLayout);
        jStaffHoursInputPanelLayout.setHorizontalGroup(
            jStaffHoursInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jStaffHoursInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jStaffHoursInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jStaffHoursInputPanelLayout.createSequentialGroup()
                        .addGroup(jStaffHoursInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jStaffHoursInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDSField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(jSIField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jNDField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jStaffHoursInputPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jOCField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jStaffHoursInputPanelLayout.createSequentialGroup()
                        .addGroup(jStaffHoursInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jStaffHoursInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jHolsField, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(jAddField))))
                .addContainerGap())
        );
        jStaffHoursInputPanelLayout.setVerticalGroup(
            jStaffHoursInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jStaffHoursInputPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jStaffHoursInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jDSField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jStaffHoursInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jNDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jStaffHoursInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSIField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jStaffHoursInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jOCField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jStaffHoursInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jHolsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jStaffHoursInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29))
        );

        jHoursWorkedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Hours worked"));

        jLabel7.setText("Total hours:");

        jLabel8.setText("SleepIn shifts:");

        jLabel9.setText("Top-up hours:");

        jLabel10.setText("OnCall shifts:");

        jTotalHrsField.setEditable(false);

        jTopUpField.setEditable(false);
        jTopUpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTopUpFieldActionPerformed(evt);
            }
        });

        jTotalOCField.setEditable(false);

        jTotalSIField.setEditable(false);

        jLabel11.setText("Overtime hours:");

        jOvertimeField.setEditable(false);

        javax.swing.GroupLayout jHoursWorkedPanelLayout = new javax.swing.GroupLayout(jHoursWorkedPanel);
        jHoursWorkedPanel.setLayout(jHoursWorkedPanelLayout);
        jHoursWorkedPanelLayout.setHorizontalGroup(
            jHoursWorkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHoursWorkedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jHoursWorkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jHoursWorkedPanelLayout.createSequentialGroup()
                        .addGroup(jHoursWorkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addGap(22, 22, 22)
                        .addGroup(jHoursWorkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTotalSIField)
                            .addComponent(jTotalOCField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHoursWorkedPanelLayout.createSequentialGroup()
                        .addGroup(jHoursWorkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jHoursWorkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTotalHrsField, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(jOvertimeField)
                            .addComponent(jTopUpField, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jHoursWorkedPanelLayout.setVerticalGroup(
            jHoursWorkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHoursWorkedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jHoursWorkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTotalHrsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jHoursWorkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jOvertimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jHoursWorkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTopUpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jHoursWorkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTotalSIField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jHoursWorkedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTotalOCField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        jGoButton.setText("GO!");
        jGoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGoButtonActionPerformed(evt);
            }
        });

        jExitButton.setText("Exit");
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        jClearButton.setText("Clear");
        jClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearButtonActionPerformed(evt);
            }
        });

        jSettingsButton.setText("Settings");
        jSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSettingsButtonActionPerformed(evt);
            }
        });

        jPayPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Pay"));

        jLabel13.setText("before tax:(£)");

        jPayField.setEditable(false);

        javax.swing.GroupLayout jPayPanelLayout = new javax.swing.GroupLayout(jPayPanel);
        jPayPanel.setLayout(jPayPanelLayout);
        jPayPanelLayout.setHorizontalGroup(
            jPayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPayField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPayPanelLayout.setVerticalGroup(
            jPayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPayPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jPayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSettingsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jHoursWorkedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jStaffHoursInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jGoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jStaffHoursInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jGoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jHoursWorkedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jClearButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSettingsButton)
                    .addComponent(jExitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDSFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDSFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDSFieldActionPerformed

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void jClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearButtonActionPerformed
        jAddField.setText("");
        jDSField.setText("");
        jNDField.setText("");
        jOCField.setText("");
        jSIField.setText("");
        jHolsField.setText("");
        jTopUpField.setText("");
        jTotalHrsField.setText("");
        jTotalOCField.setText("");
        jTotalSIField.setText("");
        jOvertimeField.setText("");
        jPayField.setText("");
        
    }//GEN-LAST:event_jClearButtonActionPerformed

    private void jGoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGoButtonActionPerformed
        CoreCalc calculator = new CoreCalc();
        
        String dayShift = jDSField.getText();
        int totalDayShift = calculator.calculateDS(dayShift);
  
        String nightShift = jNDField.getText();
        int totalNightShift = calculator.calculateND(nightShift);
        
        String sleepIn = jSIField.getText();
        int totalSleepIn = calculator.calculateSI(sleepIn);
        
        double topUp = calculator.calculateTopUp(sleepIn);
        
        String onCall = jOCField.getText();
        int totalOnCall = calculator.calculateOnCall(onCall);
        
        String additionalHrs = jAddField.getText();
        double totalAddHrs = calculator.calculateAddHrs(additionalHrs);
        
        String holidays = jHolsField.getText();
        int totalHols = calculator.calculateHols(holidays);
        
        double totalHrs = totalDayShift + totalNightShift + totalSleepIn + totalAddHrs + totalHols;
        jTotalHrsField.setText(String.valueOf(totalHrs));
        
        jTotalSIField.setText(sleepIn);
        
        jTotalOCField.setText(String.valueOf(totalOnCall));
        
        jTopUpField.setText(String.valueOf(topUp));
        
        double overtime = calculator.calculateOvertime(totalHrs);
        jOvertimeField.setText(String.valueOf(overtime));
        
        //pay calculation
        int checkedTotalSIInt = calculator.checkNum(String.valueOf(sleepIn));
        double totalPay = calculator.calculatePay(totalHrs, checkedTotalSIInt, totalOnCall, topUp);
        jPayField.setText(String.valueOf(totalPay));
    }//GEN-LAST:event_jGoButtonActionPerformed

    private void jHolsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHolsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHolsFieldActionPerformed

    private void jSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSettingsButtonActionPerformed
        
        jSettingsFrame s = new jSettingsFrame();
        s.setVisible(true);
        
        
        
    }//GEN-LAST:event_jSettingsButtonActionPerformed

    private void jTopUpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTopUpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTopUpFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoursCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoursCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoursCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoursCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoursCalcGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAddField;
    private javax.swing.JButton jClearButton;
    private javax.swing.JTextField jDSField;
    private javax.swing.JButton jExitButton;
    private javax.swing.JButton jGoButton;
    private javax.swing.JTextField jHolsField;
    private javax.swing.JPanel jHoursWorkedPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNDField;
    private javax.swing.JTextField jOCField;
    private javax.swing.JTextField jOvertimeField;
    private javax.swing.JTextField jPayField;
    private javax.swing.JPanel jPayPanel;
    private javax.swing.JTextField jSIField;
    private javax.swing.JButton jSettingsButton;
    private javax.swing.JPanel jStaffHoursInputPanel;
    private javax.swing.JTextField jTopUpField;
    private javax.swing.JTextField jTotalHrsField;
    private javax.swing.JTextField jTotalOCField;
    private javax.swing.JTextField jTotalSIField;
    // End of variables declaration//GEN-END:variables
}
